# Flight Delays

Activity Goals:
- Import libraries.
- Load the flight delay data.
- Display the dataframe.

In [3]:
import pandas as pd
import matplotlib.pyplot as mtp

flights = pd.read_csv('data/flights.csv')
flights

,scheduled,actual,carrier,flight,tailnum,origin,dest,air_time,distance
0,"04/29/2023, 16:35","04/29/2023, 17:01",WN,1079,N230WN,ATL,HOU,110.0,696
1,"07/02/2023, 15:10","07/02/2023, 15:05",DL,355,N953AT,ATL,GPT,54.0,352
2,"12/25/2023, 10:55","12/25/2023, 10:53",WN,291,N413WN,ATL,RDU,57.0,356
3,"09/01/2023, 12:50","09/01/2023, 12:48",DL,1132,N947DZ,ATL,TYS,28.0,152
4,"12/14/2023, 07:05","12/14/2023, 07:02",DL,40,N332DN,ATL,BOS,121.0,946
...,...,...,...,...,...,...,...,...,...
4995,"11/15/2023, 14:20","11/15/2023, 14:17",WN,13,N400WN,ATL,MCO,63.0,404
4996,"04/09/2023, 19:50","04/09/2023, 19:58",OH,1320,N567NN,ATL,CLT,42.0,226
4997,"12/14/2023, 13:20","12/14/2023, 13:16",DL,695,N363NB,ATL,DAL,103.0,721
4998,"12/06/2023, 13:05","12/06/2023, 13:01",DL,911,N992AT,ATL,GSO,56.0,306
4999,"05/29/2023, 14:38","05/29/2023, 14:57",NK,952,N624NK,ATL,DFW,110.0,731

The `scheduled` column represents the time the flight was scheduled, but the actual departure time is represented by the `actual` column. null We can use these columns to calculate flight delays.
Let's begin by extracting the two departure time columns.

Activity Goals:
- Extract `scheduled` and `actual` columns.
- Assign to new dataframe and name it departures.
- Display the results

In [4]:
departures = flights[['scheduled', 'actual']]
                  
departures

              scheduled             actual
0     04/29/2023, 16:35  04/29/2023, 17:01
1     07/02/2023, 15:10  07/02/2023, 15:05
2     12/25/2023, 10:55  12/25/2023, 10:53
3     09/01/2023, 12:50  09/01/2023, 12:48
4     12/14/2023, 07:05  12/14/2023, 07:02
...                 ...                ...
4995  11/15/2023, 14:20  11/15/2023, 14:17
4996  04/09/2023, 19:50  04/09/2023, 19:58
4997  12/14/2023, 13:20  12/14/2023, 13:16
4998  12/06/2023, 13:05  12/06/2023, 13:01
4999  05/29/2023, 14:38  05/29/2023, 14:57

[5000 rows x 2 columns]

What data types are being used for these departure times? Let's find out using the `info()` method. Run the code below.

In [5]:
departures.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   scheduled  5000 non-null   str
 1   actual     5000 non-null   str
dtypes: str(2)
memory usage: 78.3 KB

The time values are currently strings.

Strings are not well suited for numerical calculations. For calculations that involves dates and times, we recommend converting those strings to datetime objects.

### Convert strings to datetime

Pandas has a `to_datetime()` method that converts strings to datetime objects.

Activity Goals:
- Convert strings to datetime objects.
- Do this for both columns
- Display the updated dataframe.

In [6]:
departures['actual'] = pd.to_datetime(departures['actual'])
departures['scheduled'] = pd.to_datetime(departures['scheduled'])

Let's use `info()` to confirm the new data type. Run the code below.

In [7]:
departures.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   scheduled  5000 non-null   datetime64[us]
 1   actual     5000 non-null   datetime64[us]
dtypes: datetime64[us](2)
memory usage: 78.3 KB

# Calculate the delays

To identify the delayed flights, let's first calculate the amount of delay for each flight using our datetime columns. The equation for the amount of flight delay is:

Activity Goals:
- Calculate the amount of delay using eval().
- Assign the result to a new column.
- Display the dataframe.

In [8]:
departures['delay'] = departures.eval('actual - scheduled')
departures

               scheduled              actual             delay
0    2023-04-29 16:35:00 2023-04-29 17:01:00   0 days 00:26:00
1    2023-07-02 15:10:00 2023-07-02 15:05:00 -1 days +23:55:00
2    2023-12-25 10:55:00 2023-12-25 10:53:00 -1 days +23:58:00
3    2023-09-01 12:50:00 2023-09-01 12:48:00 -1 days +23:58:00
4    2023-12-14 07:05:00 2023-12-14 07:02:00 -1 days +23:57:00
...                  ...                 ...               ...
4995 2023-11-15 14:20:00 2023-11-15 14:17:00 -1 days +23:57:00
4996 2023-04-09 19:50:00 2023-04-09 19:58:00   0 days 00:08:00
4997 2023-12-14 13:20:00 2023-12-14 13:16:00 -1 days +23:56:00
4998 2023-12-06 13:05:00 2023-12-06 13:01:00 -1 days +23:56:00
4999 2023-05-29 14:38:00 2023-05-29 14:57:00   0 days 00:19:00

[5000 rows x 3 columns]

Airlines can leave a few minutes behind schedule without being considered late. Typically a flight is considered late if it departs more than 900 seconds (15 minutes) after the scheduled departure time.

Let's determine which flights are late using `dt.total_seconds()`.

Activity Goals:
- Create a new column to flag flights as late.
- Display the dataframe.Activity Goals:
- Create a new column to flag flights as late.
- Display the dataframe.

In [9]:
departures['is_late'] = departures['delay'].dt.total_seconds() > 900
departures

               scheduled              actual             delay  is_late
0    2023-04-29 16:35:00 2023-04-29 17:01:00   0 days 00:26:00     True
1    2023-07-02 15:10:00 2023-07-02 15:05:00 -1 days +23:55:00    False
2    2023-12-25 10:55:00 2023-12-25 10:53:00 -1 days +23:58:00    False
3    2023-09-01 12:50:00 2023-09-01 12:48:00 -1 days +23:58:00    False
4    2023-12-14 07:05:00 2023-12-14 07:02:00 -1 days +23:57:00    False
...                  ...                 ...               ...      ...
4995 2023-11-15 14:20:00 2023-11-15 14:17:00 -1 days +23:57:00    False
4996 2023-04-09 19:50:00 2023-04-09 19:58:00   0 days 00:08:00    False
4997 2023-12-14 13:20:00 2023-12-14 13:16:00 -1 days +23:56:00    False
4998 2023-12-06 13:05:00 2023-12-06 13:01:00 -1 days +23:56:00    False
4999 2023-05-29 14:38:00 2023-05-29 14:57:00   0 days 00:19:00     True

[5000 rows x 4 columns]

We now know which flights were delayed. Next up, calculating the day of week for each flight.

### Get the day of the week
In addition to supporting calculations, datetime objects allow us to get information such as the year, month, and day.

To do this, we take each datetime object and convert it to a formatted string using the string format time method, `strftime()`. The method uses format codes to represent the date and time. Below are a few examples:

`%d` - Day of the month as a zero-padded decimal number <br>
`%m` - Month as a zero-padded decimal number <br>
`%Y` - Year with century as a decimal number <br>

Activity Goals:
- Get the abbreviated weekday name for each flight.
- Assign the result to a new column.
- Display the dataframe.

In [ ]:
departures['scheduled'] = departures['scheduled'].str

               scheduled              actual             delay  is_late
0    2023-04-29 16:35:00 2023-04-29 17:01:00   0 days 00:26:00     True
1    2023-07-02 15:10:00 2023-07-02 15:05:00 -1 days +23:55:00    False
2    2023-12-25 10:55:00 2023-12-25 10:53:00 -1 days +23:58:00    False
3    2023-09-01 12:50:00 2023-09-01 12:48:00 -1 days +23:58:00    False
4    2023-12-14 07:05:00 2023-12-14 07:02:00 -1 days +23:57:00    False
...                  ...                 ...               ...      ...
4995 2023-11-15 14:20:00 2023-11-15 14:17:00 -1 days +23:57:00    False
4996 2023-04-09 19:50:00 2023-04-09 19:58:00   0 days 00:08:00    False
4997 2023-12-14 13:20:00 2023-12-14 13:16:00 -1 days +23:56:00    False
4998 2023-12-06 13:05:00 2023-12-06 13:01:00 -1 days +23:56:00    False
4999 2023-05-29 14:38:00 2023-05-29 14:57:00   0 days 00:19:00     True

[5000 rows x 4 columns]